export const sectors = [
  { id: 'intro', label: 'CITY GATE', sector: 'THE CITY', state: 'GATE OPEN' },
  { id: 'about', label: 'ARCHIVES', sector: 'THE ARCHIVES', state: 'RECORDS FOUND' },
  { id: 'missions', label: 'MARKET', sector: 'THE MARKET', state: 'WORK DISPLAYED' },
  { id: 'experience', label: 'GUILD', sector: 'THE GUILD', state: 'PRACTICE ACTIVE' },
  { id: 'services', label: 'WORKSHOP', sector: 'THE WORKSHOP', state: 'TOOLS READY' },
  { id: 'process', label: 'LIBRARY', sector: 'THE LIBRARY', state: 'METHOD MAPPED' },
  { id: 'skills', label: 'OBSERVATORY', sector: 'THE OBSERVATORY', state: 'NODES LINKED' },
  { id: 'signature', label: 'WATCHTOWER', sector: 'THE WATCHTOWER', state: 'CITY IN VIEW' },
  { id: 'contact', label: 'CHAMBER', sector: 'HIDDEN CHAMBER', state: 'LEDGER OPEN' },
  { id: 'complete', label: 'REVEALED', sector: 'THE CITY', state: 'JOURNEY COMPLETE' }
];

export const missions = [{"no": "01", "name": "KNOWLEDGE & ENTITY SEO", "type": "WIKIPEDIA / RESEARCH", "body": "Factual, search-aware knowledge content built around long-tail intent, clean hierarchy and entity clarity.", "challenge": "Explain technical and scientific topics clearly for humans and search systems.", "approach": "Research-first writing, descriptive headings and precise entity relationships.", "result": "40+ published articles across knowledge-led and search-focused topics.", "url": "https://en.wikipedia.org/wiki/Heat_exchanger", "tech": ["Research", "Entity SEO", "Content Writing"]}, {"no": "02", "name": "SEO-FIRST WEB EXPERIENCES", "type": "FRONTEND / TECHNICAL SEO", "body": "Hand-coded pages that connect design, semantic structure and search fundamentals.", "challenge": "Create fast, legible pages without burying search fundamentals.", "approach": "Semantic HTML, heading hierarchy, metadata, canonicals and performance-aware CSS.", "result": "Clean frontend foundations designed for usability and technical SEO review.", "url": "#intro", "tech": ["HTML / CSS", "Technical SEO", "Performance"]}, {"no": "03", "name": "SEARCH CONTENT SYSTEMS", "type": "B2B / B2C / D2C STRATEGY", "body": "Content architecture for manufacturing and specialist markets, built around real buyer intent.", "challenge": "Translate complex products into useful search experiences without losing technical detail.", "approach": "Intent mapping, category hierarchy, supporting guides, internal links and schema.", "result": "A clearer organic growth foundation for businesses with limited search visibility.", "url": "#contact", "tech": ["Intent Research", "Schema", "Content Strategy"]}];
export const skills = [["Technical SEO", "Crawlability, indexation, canonicals and structured data. Tools: Screaming Frog and Search Console."], ["On-Page SEO", "Titles, headings and intent alignment for relevant pages."], ["Local SEO", "Google Business Profile, local intent and location content."], ["Intent Research", "Keyword clusters, competitive gaps and buyer journeys. Tools: Ahrefs and Semrush."], ["Content Strategy", "Connected product, category and informational content."], ["Entity Writing", "Research-led writing with clear topics and relationships."], ["Search Console", "Query segmentation, CTR analysis and search performance diagnostics."], ["GA4", "Understand acquisition, engagement and conversion events."], ["HTML / CSS", "Semantic, accessible and performance-conscious pages."], ["Schema", "Structured data and entity relationships."], ["Core Web Vitals", "PageSpeed Insights and practical page experience improvements."], ["Looker Studio", "Useful reporting that connects observations with next steps."]];
